services:
  updateportainerstacks:
    image: nopenix/update-portainerstacks:latest
    ports:
      - 8080:8080 # Exposes HTTP 
    restart: unless-stopped
    environment:
      # Auto Update Settings
      AutoUpdateDefaultMode: AutoUpdate # Can be: OnlyNTFY, AutoUpdate, DoNotUpdate
      CRON_SCHEDULE: "*/0 * * * *" # CRON String. Sets when the Programm is triggered
      # Portainer Settings
      PortainerBaseAddress: https://portainer.yourdomain.com # just the base address of your portainer
      PortainerAPIKey: # Portainer API Key goes here
      # NTFY Settings
      NTFYEnabled: $true # Can be $true or $false
      NTFYTopicURL: https://ntfy.yourdomain.com/Portainer-Updates
      NTFYToken: # Can also be left empty if there is none